version: '3'
services:
  api:
    ports:
      - '8000:8000'
    image: vicentelimeira/sempreleio_backend:latest
    container_name: api
    command: ./run.sh
    restart: always
    tty: true
    working_dir: /srv/app
#    depends_on:
#      - sempreleio_db
    volumes:
      - static-content:/srv/app/static
      - media-content:/srv/app/media
    networks:
      - sempreleio_net


#Docker Networks
networks:
  my_network:
    driver: bridge
#Volumes
volumes:
  static-content:
  media-content: