version: '3'
services:
  api:
    ports:
      - '8000:8000'
    image: vicentelimeira/sempreleio_backend_postgres:latest
    container_name: api
    command: ./run.sh
    restart: always
    tty: true
    working_dir: /srv/app
    environment:
      - POSTGRES_NAME=dbSempreLeio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste@123  
    depends_on:
      - sempreleio_db
    volumes:
      - static-content:/srv/app/static
      - media-content:/srv/app/media
    networks:
      - sempreleio_net

  sempreleio_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste@123
    networks:
      - sempreleio_net      

volumes:
  postgres_data:
  static-content:
  media-content:

networks:
  sempreleio_net:
    driver: bridge